#!/usr/bin/env python
import pandas as pd
from empress.model import Model
from empress.webserver import Application
from tornado.httpserver import HTTPServer
from tornado.ioloop import IOLoop
from skbio import TreeNode
import empress.tools as tools
import click


@click.command()
@click.option(
    '--tree-file', '-f', required=True,
    help='The file that contains the tree')
@click.option(
    '--metadata', '-m', default=None,
    help='A file that contains your metadata')
@click.option(
    '--additional-metadata', '-a', default=None,
    help='An additional file that contains metadata'
)
@click.option(
    '--port', '-p', default=8080, show_default=True,
    help='The port to run the local server on.'
)
@click.option(
    '--main-skiprow', '-r', default=0, show_default=True,
    help='The number of rows to ignore in the main metadata file.'
)
@click.option(
    '--additional-skiprow', default=0, show_default=True,
    help='The number of rows to ignore on the additional metadata file.'
)
@click.option(
    '--main-seperator', '-s', default='\t',
    help='The seperator used in the metadata file. [default: <tab>]'
)
@click.option(
    '--additional-seperator',default='\t',
    help='The seperator used in the additional metedata file. [default: <tab>]'
)
@click.option(
    '--color-file', '-c', default=None, show_default=True
)
@click.option(
    '--empress-coords-file', '-e', default=None
)
def start(
        tree_file, metadata, additional_metadata, port,
        main_skiprow, additional_skiprow, main_seperator, additional_seperator,
        color_file, empress_coords_file):

    try:
        import qiime2
        from qiime2 import Metadata
        tree = qiime.Artifact.load(tree_file).view(TreeNode)
        metadata = Metadata.load('sample-metadata.tsv').to_dataframe()
    except:
        print('reading in tree')
        tree = tools.read(tree_file)
        print('done reading in tree')

    print('reading metadata')
    if metadata is not None:
        metadata = tools.read_metadata(metadata, main_skiprow, main_seperator)
    if additional_metadata is not None:
        additional_metadata = tools.read_metadata(
            additional_metadata, additional_skiprow, additional_seperator)
        metadata = pd.merge(additional_metadata, metadata,
                        how='outer', on="Node_id")
    print('done reading metadata')

    if color_file is not None:
        nodes = tools.read_metadata(
            color_file, seperator='\t')
        nodes['index'] = nodes['Node_id']
        nodes = nodes.set_index('index')
    else:
        nodes = None

    m = Model(tree, metadata, highlight_ids=nodes, coords_file=empress_coords_file)

    # Create the webserver
    print("build web server")
    http_server = HTTPServer(Application(m))
    http_server.listen(port)
    ioloop = IOLoop.instance()
    print("server started at port", port)
    ioloop.start()
    print("done")


if __name__ == '__main__':
    start()
