#!/usr/bin/env python
from empress.model import Model
from empress.webserver import Application
from tornado.httpserver import HTTPServer
from tornado.ioloop import IOLoop
import click


@click.command()
@click.option(
    '--tree-file', '-f', required=True,
    help='The file that contains the tree')
@click.option(
    '--metadata', '-m', required=True,
    help='A file that contains your metadata')
@click.option(
    '--clade-field', '-c', required=True,
    help='The metadata field that contains the clade names. '
    'This is the field that will be to color clades.')
@click.option(
    '--additional-metadata', '-a', default=None,
    help='An additional file that contains metadata'
)
@click.option(
    '--port', '-p', default=8080, show_default=True,
    help='The port to run the local server on.'
)
@click.option(
    '--main-skiprow', '-r', default=0, show_default=True,
    help='The number of rows to ignore in the main metadata file.'
)
@click.option(
    '--additional-skiprow', default=0, show_default=True,
    help='The number of rows to ignore on the additional metadata file.'
)
@click.option(
    '--main-seperator', '-s', default='\t',
    help='The seperator used in the metadata file. [default: <tab>]'
)
@click.option(
    '--additional-seperator',default='\t',
    help='The seperator used in the additional metedata file. [default: <tab>]'
)
def start(
        tree_file, metadata, clade_field, additional_metadata, port,
        main_skiprow, additional_skiprow, main_seperator, additional_seperator):
    m = Model(
      tree_file, metadata, clade_field, additional_metadata, port,
      main_skiprow, additional_skiprow, main_seperator, additional_seperator)
    m.center_tree()

    # Create the webserver
    print("build web server")
    http_server = HTTPServer(Application(m))
    http_server.listen(port)
    ioloop = IOLoop.instance()
    print("server started at port", port)
    ioloop.start()
    print("done")


if __name__ == '__main__':
    start()
