name: Update Docs

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

jobs:
  # name of job
  build:
    # The type of runner that the job will run on (available options are window/max/linux)
    runs-on: ubuntu-latest

    env:
      DOCS_CHAGNED: -1 # false
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # first grab branch from github
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up credientials
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Set up conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.6
          conda-channels: anaconda, conda-forge

      - name: Create Qiime enviroment
        run: |
          wget https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py36-linux-conda.yml
          conda env create -n qiime2-dev --file qiime2-latest-py36-linux-conda.yml      

      - name: Install Empress
        run: |
          conda run -n qiime2-dev pip uninstall emperor --yes
          conda run -n qiime2-dev pip install -e .[all] --verbose
          conda run -n qiime2-dev qiime dev refresh-cache

      - name: Create Docs 
        run: |
          conda run -n qiime2-dev make docs
          git add docs
          git diff
          if ! git diff-index --cached --quiet HEAD --ignore-submodules --
          then
            git commit -m "update docs"
            echo "DOCS_CHAGNED=0" >> $GITHUB_ENV
          fi

      - name: Push changes
        if: ${{ env.DOCS_CHAGNED == 0 }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
